[package]
name = "cpp-class"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2018"

[dependencies]
cpp-class-macro = { path = "macro" }
link-cplusplus = { version = "1.0", features = ["libstdc++"] }

[workspace]
members = ["macro"]
